name: E2E tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: rox-go
      - name: Checkout e2e tests
        uses: actions/checkout@v2
        with:
          repository: rollout/sdk-end-2-end-tests
          ref: master
          token: ${{ secrets.E2E_PAT }}
          path: sdk-end-2-end-tests
      - name: link driver
        working-directory: ./sdk-end-2-end-tests/drivers
        run: ln -s $GITHUB_WORKSPACE/rox-go/v5/driver go
      - name: build e2e node driver
        working-directory: ./sdk-end-2-end-tests/drivers/nodejs
        run: |
          yarn install --frozen-lockfile
      - name: build and run e2e
        working-directory: ./sdk-end-2-end-tests
        run: |
          yarn install --frozen-lockfile
          QA_E2E_BEARER=$QA_E2E_BEARER SDK_LANG=go NODE_ENV=qa yarn test
        env:
          QA_E2E_BEARER: ${{ secrets.QA_E2E_BEARER }}
#          TODO: implement EU hosting support
#      - name: build and run e2e eu hosting
#        working-directory: ./sdk-end-2-end-tests
#        run: |
#          QA_E2E_BEARER=$QA_EU_E2E_BEARER SDK_LANG=go NODE_ENV=qa HOSTING=eu yarn test:env
#        env:
#          QA_EU_E2E_BEARER: ${{ secrets.QA_EU_E2E_BEARER }}
      - name: Show e2e server driver logs
        if: ${{ always() }}
        run: cat ./sdk-end-2-end-tests/drivers/go/log_1234.out || echo "no log file"
